### ISSUE TITLE
새로고침 및 url 이동시 vuex변수 초기화

### ISSUE THREAD

**Issue by jny9708** [leejuhyeok/91cm#10]
새로고침 및 url이동시 vuex 변수가 초기화되네요.
전역변수처럼 사용할 변수는 vuex에 선언하는 걸로 알고 있어서 싱글페이지니까 로그인 성공후 로그인한 유저객체는 한번만 받아와서 vuex변수로 사용하면 되겠다했는데 그렇게는 못할 것 같네요. 
url이동마다 해당 컴포넌트에서 유저객체를 가져오는 코드가 있어야할 것 같아요. 웹소켓 연결 코드도 마찬가지구요. 

다행히 로그인한 후 이동할 수 있는 페이지들은 모두 사이드바와 헤더가 있어서 그것들을 감싸는 Main.vue에 해당 코드를 집어넣으면 이동마다 연결이 가능할 것 같습니다. 유저객체도 가져올 수 있구요.

나중에 vuex변수 사용하실 때 참고되시라고 올립니다.

**Comment by jny9708** [comment]
혹시 초기화 문제가 저만 나타나는 거일 수도 있으니 확인부탁드려요!

**Comment by leejuhyeok** [comment]
일단 지금 간단히 테스트 해봤는데 저도 새로고침하면 변수가 초기화 되는것으로 보입니다. 조금 더 자세히 테스트 해보고 여러 방법들을 시도해 보고 다시 말씀드리겠습니다
