### ISSUE TITLE
commit내역에 single comment 남겼습니다!

### ISSUE THREAD

**Issue by jny9708** [leejuhyeok/91cm#2]
아까 발생되었던 문제와 관련한 comment남겼습니다.
https://github.com/leejuhyeok/91cm/commit/befdc82c2e194da2c14756e6e5cbd5caab9cf46c#r37420250

**Comment by leejuhyeok** [comment]
말씀해주신 방법으로 하면 될것 같네요. 수고하셨습니다  👍👍
