### ISSUE TITLE
수정해야할 버그들

### ISSUE THREAD

**Issue by leejuhyeok** [leejuhyeok/91cm#34]
## 버그
1. [x] 초대 받은 후 새로고침 후 생성된 채널로 가보면 메시지가 2개씩 생성됨
2. [x] `/main` url 입력 시 로그인 하지 않아도 signUp 페이지로 이동됨

**Comment by jny9708** [comment]
- [ ] 채널리스트의 length가 0 인데 userlist를 가져오고있어서 오류발생
- [ ] 버그는 아니지만 사용자가 채널에서 나갈때 '유저가 나가셨습니다'와 같은 알림 기능추가
- [ ] 채널이 없는데 profile을 들어가면 메인으로 다시 돌아오는 루트가 새로고침뿐이다.

**Comment by leejuhyeok** [comment]
# 우선순위 
---
# 높음
[ ] 채널 정보, 사용자 정보 변경 시 실시간적으로 반영 안되는 문제

## 중간

### 낮음 
[  ] 간헐적으로 메시지 최하단에 있어도 최하단 이동 알림 바?가 생기는 문제

**Comment by jny9708** [comment]
- [ ] 닉네임 수정했는데 실시간적으로 안바뀌는 문제
- [ ] 초대시 띄어쓰기 있는 닉네임은 초대가 안되는 문제

2번째 문제는 닉네임 유효성체크할 때 띄어쓰기를 허용하지 않는다거나,
띄어쓰기 대신 다른 기호(?)로 문자열을 잘라서 여기에 쓰인 기호는 닉네임으로 사용하지 못하게 하거나, 아예 예전버전으로 초대하거나 등등 상의해서 해결해야 할 것 같습니다.
