### ISSUE TITLE
회원가입에 사용할 도메인 질문

### ISSUE THREAD

**Issue by jny9708** [leejuhyeok/91cm#5]
회원가입 기능 구현하려고 합니다. 궁금한 점이 있어 여쭤봐요!

1. com.nineone.nocm.controller.api에 있는 uerapicontroller를 만들어 놓으셨던데 그 클래스에다가 코드 짜면 될까요?

2. com.nineone.nocm.domain에 user 객체 있던데 이거는 소셜로그인할 때만 사용되는 객체인가요?
회원가입 요청이 들어올 때 파라미터로 받을 커맨드객체를 user로 사용하면 되는지 따로 객체를 생성해야할지 잘 모르겠네요..ㅠ

**Comment by leejuhyeok** [comment]
1. userapicontroller에서 처리하는게 좋을거 같습니다. 그리고 Service로 넘겨서 처리하는게 좋을거 같으면 추후에 논의해서 그렇게 하죠. 그전까지는 userapicontroller에 기능 구현하시면 될 것 같습니다.
> 클래스 이름은 임시로 작성한거라 좋은 이름 있으면 추천 받습니다.

2. User 객체는 다같이 모든 사용자 객체입니다. 이것도 임시로 만든 객체라서 안의 멤버 변수들은 몇가지 변경될 수도 있습니다. 때문에 각자 기능을 구현하고 기능이 완성되면 멤버변수를 조정하는 방식으로 하면 어떨까 합니다.

**Comment by jny9708** [comment]
네 감사합니다. 그럼 userapicontroller에 코딩하고 있을게요~
그리고 고려해야할 부분은 mysql 테이블 칼럼명이랑 객체 필드명들이 일치해야 mybatis가 값을 제대로 가져오는 것으로 알고있어서 그런 것들은 추후에 일치시켜야 할 것 같습니다~
