### ISSUE TITLE
소셜 로그인 유저 객체 DB 저장 문제

### ISSUE THREAD

**Issue by leejuhyeok** [leejuhyeok/91cm#7]
## 문제
- 소셜로그인 유저는 userid, password를 가져올 수 없음
- 현재 DB에는 userid, password가 NOT NULL로 되어 있어서 객체 저장시 오류가 발생함

## 예상 해결 방안
- member 테이블을 변경해서 userid, password에 NULL을 허용하도록 변경

#### 해당 예상 해결 방안의 문제점이나 더 나은 해결 방법, 궁금한 점이 있으시면 코멘트로 남겨주시면 감사하겠습니다.

**Comment by jny9708** [comment]
전에 제가 보내드렸던 테이블sql로 테이블 생성하셨다면 userid가 pk이기 때문에 null허용이 안될거에요 null을 허용하려면 pk를 다른 걸로 추가하고 null로 만들던가해야 할 것 같습니다.
만약에 userid가 null이 되면 회원 고유의 primary key는 무엇이 되는지도 생각을 해야할 거 같아요.

**Comment by leejuhyeok** [comment]
맞네요 pk가 userid라서 변경이 필요할거 같네요. member 테이블에 대한 변경에 대해서 논의를 추후에 해봐야겠네요.

**Comment by jny9708** [comment]
소셜로그인할 때 구글과 같은 서버에서 넘어오는 값들은 무엇무엇이 있나요?
해당 서버에서 넘어온 값들 중에 DB에 저장해야하는 값들은 무엇무엇이 있는지 알 수 있을까요?

**Comment by leejuhyeok** [comment]
소셜 로그인에 성공하면 response가 오는데 json 형식으로 옵니다. 그 key와 value는 SNS 마다 다른점이 많습니다. 그래서 확인하고 코드에 적용해줘야 합니다. 아래가 그 key와 value 값을 print한것인데, 깃허브는 쓸데없는 값도 많이 와서 안보셔도 될거 같습니다. 
- #### 네이버 : 이메일, 이름 (다른 값도 받아올 수 있도록 api를 변경할 수 있는지 확인해보겠습니다)
- #### 구글 : 이름, 이메일, 국적, 프로필 사진
```
// 구글
key = sub 	 value = 116596593806733736514
key = name 	 value = 이주혁
key = given_name 	 value = 주혁
key = family_name 	 value = 이
key = picture 	 value = https://lh6.googleusercontent.com/-hOxKAqIgn4Y/AAAAAAAAAAI/AAAAAAAAAAA/AKF05nDu4y_tsvdt89PhTXFat_paDtLPuw/photo.jpg
key = email 	 value = leejuhyeok@nineonesoft.com
key = email_verified 	 value = true
key = locale 	 value = ko
key = hd 	 value = nineonesoft.com

//네이버
key = resultcode 	 value = 00
key = message 	 value = success
key = response 	 value = {id=54942631, email=tyrfingr12@naver.com, name=이주혁}

// 깃허브
key = login 	 value = leejuhyeok
key = id 	 value = 43229413
key = node_id 	 value = MDQ6VXNlcjQzMjI5NDEz
key = avatar_url 	 value = https://avatars0.githubusercontent.com/u/43229413?v=4
key = gravatar_id 	 value = 
key = url 	 value = https://api.github.com/users/leejuhyeok
key = html_url 	 value = https://github.com/leejuhyeok
key = followers_url 	 value = https://api.github.com/users/leejuhyeok/followers
key = following_url 	 value = https://api.github.com/users/leejuhyeok/following{/other_user}
key = gists_url 	 value = https://api.github.com/users/leejuhyeok/gists{/gist_id}
key = starred_url 	 value = https://api.github.com/users/leejuhyeok/starred{/owner}{/repo}
key = subscriptions_url 	 value = https://api.github.com/users/leejuhyeok/subscriptions
key = organizations_url 	 value = https://api.github.com/users/leejuhyeok/orgs
key = repos_url 	 value = https://api.github.com/users/leejuhyeok/repos
key = events_url 	 value = https://api.github.com/users/leejuhyeok/events{/privacy}
key = received_events_url 	 value = https://api.github.com/users/leejuhyeok/received_events
key = type 	 value = User
key = site_admin 	 value = false
key = name 	 value = tyrfingr
key = company 	 value = null
key = blog 	 value = 
key = location 	 value = null
key = email 	 value = null
key = hireable 	 value = null
key = bio 	 value = null
key = public_repos 	 value = 37
key = public_gists 	 value = 0
key = followers 	 value = 0
key = following 	 value = 4
key = created_at 	 value = 2018-09-13T04:57:12Z
key = updated_at 	 value = 2020-02-28T13:13:06Z
key = private_gists 	 value = 0
key = total_private_repos 	 value = 2
key = owned_private_repos 	 value = 2
key = disk_usage 	 value = 65468
key = collaborators 	 value = 0
key = two_factor_authentication 	 value = false
key = plan 	 value = {name=pro, space=976562499, collaborators=0, private_repos=9999}


```

**Comment by leejuhyeok** [comment]
응답을 가져와서 파싱하는 기능은 OAuthAttributes.java 에 있습니다.

**Comment by jny9708** [comment]
그 소셜로그인은 쿠키/세션방식이 아니라 토큰방식이라고 들었습니다. 토큰발급 및 관리는 어떻게 되는건지 궁금합니다. 더 나아가서  vue같은 경우 spa라서 페이지이동마다 spring security를 안걸치고 라우터에 의해서 이동이 될텐데 spa에 따른 로그인유지방법(?) 유효토큰확인? 권한확인? 이라고 해야하나요 그런거에 대해서 생각을 해야할 것 같습니다.

**Comment by leejuhyeok** [comment]
###  토큰발급 및 관리는 어떻게 되는건지 궁금합니다.
현재 코드에서는 소셜 로그인 유저를 세션에 저장해서 세션 방식을 취하고 있습니다. 아래는 세션에 저장하는 코드 부분입니다.
```java
OAuthAttributes attributes = OAuthAttributes.Of(registrationId, userNameAttributeName,
                oAuth2User.getAttributes());

        User user = saveOrUpdate(attributes);
        httpSession.setAttribute("user", user);
        return new DefaultOAuth2User(
                Collections.singleton(new SimpleGrantedAuthority(user.getRoleKey())),
                attributes.getAttributes(),
                attributes.getNameAttributeKey());
``` 
제가 지금 하고 있는 소셜 로그인 방식에 대해서 좀 더 설명하자면 
1. SNS REST API 서버에 key와 필요 정보를 보내면 SNS로그인 창이 뜨고 사용자가 SNS에 로그인에 성공하면 SNS api에 설정했던 redirect url로 이동시켜 줍니다.
2. redirect url로 이동할때 응답으로 사용자 정보를 줍니다.
3. 서버에서 해당 정보를 받아옵니다. 정보는 key & value의 형태를 하고 있기 때문에 SNS에 알맞게 키를 지정해서 값을 가져와서 User 객체를 생성해줍니다.
4. user 객체를 생성하고  해당 객체를 세션에 'user'라는 키로 저장합니다. 
이러한 방식으로 로그인을 진행합니다.



### spa에 따른 로그인 유지 방법
일단 세션 방식이라서 SPA에 따른 로그인 문제는 따로 없을거라고 생각됩니다. 그리고 
지금 테스트를 진행해 봤는데, 이전에 설정해줬던 RouterController.java 때문에 url은 먼저 서버로 들어옵니다. 때문에 Security에서 먼저 걸러짐으로 크게 문제가 될 부분은 지금은 없을듯 합니다.

말을 정말 못해서 궁금증이 해결되실지 걱정이네요 😅 이해가 안되시는 부분이나 이상한 부분이 있다면 편히 말씀해주세요

**Comment by jny9708** [comment]
아 세션방식으로 진행되는군요. 설명을 잘해주셔서 이해가 잘 됐습니다.
근데 spa에 따른 로그인 유지방법은 잘 모르겠습니다..ㅠ
제가 공부하면서 이해한 바로는 (제가 잘못 이해한 걸 수 도 있으니 잘못된거 같으면 지적해주세요ㅠ) vue가 빌드되면 main/resource/static폴더로 저장이 되고
spring boot는 컨트롤러 지정없이도 루트컨텍스트('/')에 접속하면 main/resource/static에 있는 index.html을 화면에 띄워줍니다. 그래서 저희가 / 매핑이 없어도 index.html을 볼 수 있는거구요.
저희는 vue 설정과 코딩을 통해 그 index.html에 spa형식으로 화면을 볼 수 있게되구요.
그 화면에서 버튼이나 링크를 통해 url을 이동하면 라우터에 의해 주소가 변경되고 이 변경과정에서 스프링부트와 일체 통신이 없다고 이해했습니다. 라우터에 의해 주소가 변경되는 거니까요.
이 url 변경과정 속에서 그냥 spring 프로젝트에서 주소변경할 때처럼 그 사이에 로그인상태를 확인해야할 텐데 라우터에 의해 변경되니 확인할 방법이 필요합니다. 이는 보통 네비게이션 가드라는 기능을 통해 확인한다더군요.
지금까지는 화면 안에서 링크 또는 버튼을 통해 라우터를 이용한 url이동 이었다면
주소창을 이용한 url이동은 스프링부트 서버로 요청이 바로 다이렉트로 들어가는 거기 때문에
routercontroller와 같은 컨트롤러를 타게됩니다. 해당 요청의 컨트롤러 설정이 없다면 서버에서는 에러페이지를 띄우겠죠
routercontroller의 설정인 들어오는 모든 요청은 /로 리다이렉션하라라는 코드가 있기 때문에 에러페이지가 안보이게 되는 것이고 vue프로젝트의 해당 url화면이 보이게 되는 걸로 이해하고 있습니다.

그렇기 때문에 화면단에서 axios와 같은 통신을 이용해 데이터를 가져와서 권한이든 뭐든 확인처리를 해줘야한다라고 이해했습니다.ㅠㅠ

**Comment by leejuhyeok** [comment]
먼저 이 부분에 대해서 아직 정확하지 않다는 것을 말씀드립니다.
일단 url이 spring boot를 거치고 해당하는 url이 없으면 routerController를 통해서 vue의  router로 전달된다라고 생각하시면 될것 같습니다. 
> spring boot를 먼저 거치게 됨으로 Security가 먼저 동작됩니다.
현재 프로젝트를 실행 했을때 url을 직접 입력하거나 href="url" 같은 태그?로 인한 이동을 해봤는데, 로그인을 안한 상태이면 /main 을 입력하고 버튼으로 인한 이동도 막혀서 다시 로그인 페이지로 돌아오는 동작을 확인했습니다. 
**다만 router-link 태그를 통한 이동은 Spring boot를 거치지 않고 바로 router로 이동 하기 때문에 router-link를 통한 이동은 로그인을 하지 않아도 /main으로 이동 가능하였습니다.**


`"forward:/"` 이 부분이 `/`로 리다이렉트 되는게 아니라 현재 url을 router로 보내는 부분이라고 생각하시면 될것 같습니다.
그리고 axios와 같은 통신을 사용하는 이유는 url를 router로 보내는것은 가능하지만 데이터는 보내는 것은 불가능하기 때문입니다. 가능한 방법이 있을지도 모르지만 찾지못하였습니다.... 
그리고 vue에서 spring boot로 url과 데이터를 보내는 방법은 현재 axios 밖에 없다고 알고 있습니다.

<br><br>
답변이 잘 됐는지 모르겠네요 몇 가지 저도 테스트를 해보느냐고 답변에 시간이 좀 걸린 점 죄송합니다. 또 궁금하신 점이 있거나 이상한 부분이 있으시면 말씀해 주세요

**Comment by jny9708** [comment]
네네 이해가 잘됐습니다! 밤 늦게까지 고생하시네요ㅠㅠ 답변해주셔서 감사합니다. 
한가지 또 궁금한 것이 있는데요.  귀찮게 하는 것이 아닐까 싶지만 질문 드려봅니다ㅠㅠ
해당 소셜(sns)마다 로그인했을 때 서비스서버에서 넘어오는 그 회원만의 유니크값이 있을까요?
그 유니크값이 있다면 그 유니크값을 가지고 디비에 저장되어있으면 바로 로그인처리를 하고
디비에 저장되어있지 않은 유니크값이면 저희 서버에서 클라이언트로 추가정보를 입력하게 하고
추가정보와 유니크값을 저장하면 되지않을까 싶어서요.

**Comment by leejuhyeok** [comment]
네네 말씀하신데로 
```
key = sub value = 116596593806733736514
key = response value = {id=54942631
key = id value = 43229413
```
이 부분이 각 SNS의 유니크 값으로 보입니다. 아주 희박하게 네이버와 깃허브 id 값이 겹칠 수도 있을거 같은데 이것은 혹시의 이야기입니다. 가능성은 아주 희박하다고 봅니다. 지금 소규모 서비스에서는 id 값을 pk로 잡아도 문제는 크게 없을거라고 생각합니다.

<br>
이건 그냥 추가적으로 말씀드리는 이야기인데 저번 프로젝트에서는 email을 가지고 select를 하였고 pk는  auto_increment를 이용한 int id를 사용했습니다.
두 방법 모두 문제 점도 있고 장점도 있어서 이것은 같이 고민을 해봐야 할것 같습니다 😓

**Comment by jny9708** [comment]
네 해당 문제는 회의를 통해서 정해야 할 것 같네요.
궁금한게 또 생겼는데요.
제가 알기로는 spring security를 이용해서 로그인에 성공하면
principal객체가 authentication객체 안에 담겨서 securitycontext에 저장되는 걸로 알고있는데
소셜로그인도 똑같이 로그인에 성공하면 principal객체가 securitycontext에 저장되나요?
제가 예전에 했던 프로젝트에서 로그인하면 princial객체는 username이 담기던데
소셜로그인은 무엇이 담기는지 궁금합니다.

**Comment by leejuhyeok** [comment]
이 문제에 대해서는 좀 더 알아봐야 할 것 같습니다. 그래서 지금은 알고 있는 부분까지만 말씀드리겠습니다. 
 스프링 3.X 이전에는 principal 객체를 이용해서 로그인 사용자 정보를 가져온것으로 알고 있습니다. 이후 버전 부터는 @AuthenticationPrincipal 어노테이션을 사용해서 사용자 정보를 주입받을 수 있게되었습니다. 
그런데 코드를 실행할때 @AuthenticationPrincipal를 이용하면 소셜 로그인 사용자의 정보는 가져올 수 없습니다. 그래서 만든 어노테이션이 @Socialuser이고요
> 현재 소셜  로그인 유저를 주입받는 어노테이션은 @Socialuser입니다. 해당 User 객체를 주입받는다 라고 생각하시면 될것 같습니다.

이러한 점을 봤을때 따로 주입하는 방법이 있을지는 몰라도 자동적으로 주입되지는 않는다고 생각됩니다. 

이해가 안되거나 잘못된 설명 부분이 있다면 편하게 말씀해주시길 바랍니다.

**Comment by jny9708** [comment]
회의한 내용을 토대로 pk선정이나 유저정보 등록같은걸 생각을 해봤는데요. 문제점이 하나 있습니다.
만약에 처음 로그인을 한 유저가 sns로그인에 성공을 하면 security의 인증도 된 상태니까 성공 URI로 넘어가게되잖아요? 넘어간 그 화면에서 email이라든지 채워져야할 정보가 채워지지않은 상태다 하면 따로 추가입력 받는 input을 제공해 사용자 정보를 받아온다 하셨는데, 제가 이해한게 맞다면 여기서 문제는 그 해당 페이지에서 입력하지 않고 인증된 사용자만 들어갈 수 있는 URI에 들어간다면(페이지이동을 하게 된다면) **security는 이 유저가 인증된 사용자이기 때문에 막지 않을 수도 있다는 점**입니다. 

여기서 정해야할 것 이있다면 시큐리티에 인증된 사용자(소셜로그인에 성공했지만 추가정보는 입력하지 않은 사용자)는 채팅 및 다른 서비스들을 이용할 수 있게하는가 없게하는가 입니다.

### A
없게한다면 인증된 사용자만 들어갈 수 있는 페이지마다 채워야할 정보가 채워져있는지 확인하는 로직이 있어야합니다. 정보가 없다면 라우터로 로그인페이지 또는 추가입력 받는 uri로 이동하는 식으로요. 다른 방법이 있다면 다른 방법으로든 사용자 이동을 막아야합니다.

### B 이용할 수 있게한다면 :
security인증 허가가 난후 성공 uri로 이동하면 그때부터 사용자가 서비스를 사용할 수 있게하고 아직 채우지 못한 사용자 정보는 null인채로 냅두게 하는 방법이 있습니다. 자율적으로 profile같은 화면에서 기입하게끔 하는거죠. 하지만 이 방법은 나중에 초대를 어떤 방식으로 할 지에 따라 단점이 있습니다. 이메일을 입력해 초대한다면 디비에 저장되어있는 정보가 없으니 초대가 안되겠죠?

### 그리고 이메일과 이름을 복합키로 정하는 것에 대해서 의견을 내주셨는데
loaduser에서 db저장로직을 넣느냐 안넣느냐에 따라 복합키사용 가능여부가 결정날 것 같습니다.
loaduser에서 sns서버에서 넘어온 값들을 db에 저장한다고했을 때 pk를 복합키로 정하게된다면 이메일을 제공해주지않는 sns도 있다보니 insert오류가 날 것 같습니다.
pk는 기본적으로 not null이라는 규칙이 있는 걸로 알고 있어서요. 이럴 경우에는 사용을 못할 것 같구요. 
만약에 로그인에 성공해서 성공 url로 넘어가게되고 생성된 user객체를 요청해 받아와서 사용자 추가정보를 입력받고 제대로 갖춘 유저객체가 생성되면 그때 서버로 보내 디비에 저장한다면은 복합키 사용이 가능할 것 같습니다. 
근데 이런 경우에는 앞서 말씀드렸던 A ,B 중 A를 선택했을 때에만 가능할 것 같습니다.
DB에 유저정보가 없는데 채팅이라던지 그런 서비스를 이용하게되면 큰일날 것같아요

복합키를 사용을 하든 안하든 저장로직을 어디서 실행되는가(?)를 정해야할 것 같습니다.

이게 참 고려해야할 부분이 많아서 어렵네요..ㅠㅠ 이거 쓰면서 제가 생각하고 있는게 맞나 생각을 해보려고해도 머리가 지금 굳어가고있어섴ㅋㅋ 분별이 안가네요 제가 잘못생각하고 있는 부분이 있다면 말씀해주세요!

음 그리고 복합키말고 SNS고유식별자나 스스로 증가되는 idx를 만들어서 사용을 하게 된다면 아래와 같은 예시로 사용이 가능할 것 같습니다.

```
create table user(
id int primary key auto_increment not null,
name varchar(100), 
email varchar(100)
);

create table room(
id int primary key auto_increment not null,
name varchar(100)
);

create table notification(
id int primary key auto_increment not null,
room_id int,
sender int, 
recipient int,
foreign key (sender) references user(id) on delete cascade on update cascade,
foreign key (recipient) references user(id) on delete cascade on update cascade,
foreign key (room_id) references room(id) on delete cascade on update cascade
);

insert into user(name,email) values('홍길동','test1@test1.com');
insert into user(name,email) values('홍이동','test2@test2.com');
insert into room(name) values('채널1');
insert into notification(room_id,sender,recipient) values(1,1,2);
```

아래는 요청을 하는 유저의 초대정보를 가져오는 쿼리입니다.
만약에 넘어오는 값이 이메일밖에 없다면 다음과 같이 진행을 할 수가 있습니다.
```
select noti.*,u1.name 수신자이름 ,u2.name 송신자이름 
from notification noti 
join user u1 on noti.recipient = u1.id
join user u2 on noti.sender = u2.id
where noti.recipient = (select id from user where email = 'test2@test2.com');  
+----+---------+--------+-----------+------------+------------+
| id | room_id | sender | recipient | 수신자이름 | 송신자이름 |
+----+---------+--------+-----------+------------+------------+
|  2 |            1 |           1 |            2 | 홍이동         | 홍길동     |
+----+---------+--------+-----------+------------+------------+

(1. 수신자 이름과 송신자이름은 알아보기 쉽게하기 위해 붙인 별칭입니다.
 2. 'test2@test2.com'와 아래 2는 사용자에게 받아온 정보입니다.)
```

초대정보를 요청하여 받아볼 수 있는 사람은 로그인한 그 유저밖에 없을 것입니다.
하지만 아마 유저 pk번호가 session user 객체에 담겨져있을거기때문에 vue에도 그 객체가
넘어갔다면 그 객체의 pk를 요청과 넘겨주면
```
select noti.*,u1.name 수신자이름 ,u2.name 송신자이름 
from notification noti 
join user u1 on noti.recipient = u1.id
join user u2 on noti.sender = u2.id
where noti.recipient = 2;  
// 같은 결과 출력
```
이러한 쿼리로도 정보를 가져올 수 있습니다.

초대요청의 흐름은 다음을 생각하고 있습니다.
복합키말고 SNS고유식별자나 스스로 증가되는 idx를 만들어서 사용할 때 : 
현재 로그인한 유저의 pk와 요청받을 유저의 email 혹은 이름,  channel_id가 서버로 넘어오게 된다면
저 email 혹은 이름은 pk가 아니기 때문에 해당 email을 가진 유저의 pk를 조회해오고, 그 값과 함께 초대테이블에 저장을 해야합니다. 조회하는 과정에서 요청받을 유저가 실제 있는 유저인가 확인할 수 있는 지표가 될 수 있겠죠. 조회한 값이 없다면 실제 있는 유저가 아니라는 말이니까요.

복합키를 이용하는 경우 넘어오는 값이 email이든 이름이든 복합키이기 때문에 사용자가 두개의 정보를 보내오지 않는 이상 복합키도 idx처럼 조회를 걸친 insert를 진행해야합니다.

두개의 정보를 보내온다해도 초대를 받을 유저가 실제 존재하는 유저인지 확인해야 함으로 member테이블을 조회해야합니다. 조회하지 않고 존재하지 않는 유저를 바로 insert하면 외래키 오류에 따라 오류를 뿜고 insert실패가 될 것입니다. 이를 지표로 그 유저가 존재하지 않다라는 것은 알 수 있겠지만 이는 좋은 방법이 아닌 것 같습니다.

이를 미루어 봤을 때 저는 일단 pk는 고유식별자나 증가하는 id로 사용하는 것이 어떨까 싶습니다.

**Comment by jny9708** [comment]
이메일을 입력해서 초대하는 방식일 때,
저장되는 이메일이 중복돼서 초대요청때 받아온 이메일값과 매칭되는 pk가 두개이상이면 안되니까
추가정보를 받아올 때 이메일 중복확인을 하고 중복이 있으면 제출이 안되게끔 하거나,

이메일 중복을 허용하고 초대인풋창 아래에 자동완성기능 마냥 생기게해서 해당 유저를 사용자가 선택할 수 있게끔 하는 것 방법도 있을 것 같습니다.
아마 자동완성처럼 아래 보여주기 위해서는 미리 사용자정보리스트를 서버에서 가져와 인풋이벤트가 있을 때 입력한 문자에 맞는 사용자정보를 뜨게끔 해야 할 것 같습니다.
이때 가져오는 사용자정보 리스트에는 사용자 pk도 담기게 해서 이메일이 중복돼도 선택한 pk는 다르기 때문에 문제가 없을 것 같습니다.

**Comment by leejuhyeok** [comment]
일이 있어서 코멘트를 늦게 달아서 죄송합니다 😓
## 추가 정보가 없는 유저를 어떻게 처리할 것인가?
말씀을 듣고 보니 사용자가 추가정보를 입력하지 않고 다른 곳으로 이동할때 방어 장치가 필요하겠군요.
일단 저의 의견은 A입니다. B로 하였을때 초대와 다이렉트 채팅 등에서 문제가 발생할 것 같습니다.
<br>
그리고 A 방법으로 하였을때 사용자가 정보가 모두 있는지 확인을 해야하는데 지금 생각해 본 방법은 main으로 왔을때 axios를 통해서 정보가 모두 있는지 파악 하고 모두 있지 않다면 vuex에 state 변수를 하나 저장하고 true, false 값을 줘서 확인하는 방법은 어떨까 합니다. 
지금 간단히 생각해본것이라 문제점을 말씀해주시면 감사합니다.

## 이메일과 이름을 복합키로 정하는 것에 대해서 의견
제가 생각한것은 복합키라기 보다 사용자를 초대할때 이름을 입력하면 자동완성 기능 처럼 해당 이름의 사용자 리스트에 사용자 이름과 사용자의 이메일이 표시되어서 초대하는 사람이 확인하는? 그런 용도로  생각했습니다.  

## 이메일 입력 초대 방식
네 이메일 중복이 가능할 수 있습니다. 그래서 다른 사이트에서 사용하는 방법은 이미 해당 이메일의 user 정보가 db에 저장 되어 있다면 새로운 User를 만드는 것이 아닌 이미 저장되어 있는 User를 가져오는 방식입니다. 
즉, 같은 이메일 이라면 같은 사용자일것이고, 그러면 소셜 로그인 SNS만 다른 것이니 같은 유저로 보는것이지요. 
아니면 말씀하신 방법중에서 2번째 방법도 괜찮은것 같습니다. 

<br>
이상하거나 이해안가시는 부분이 있으면 말씀해주세요. 저도 늦은 시간에 확인해서 다시 읽어보고 궁금한 점이 생기면 코멘트 남기도록 하겠습니다.
